import React,{useRef,useState} from 'react';
import {Head,Link} from '@inertiajs/react';
const csrf=()=>document.querySelector('meta[name="csrf-token"]')?.content;
async function request(url,body){const r=await fetch(url,{method:body?'POST':'GET',headers:{'Content-Type':'application/json','Accept':'application/json','X-CSRF-TOKEN':csrf()},...(body?{body:JSON.stringify(body)}:{})});const data=await r.json();if(!r.ok)throw Error(Object.values(data.errors||{}).flat().join(' ')||'No se pudo completar la operación.');return data;}

function Ticket({ticket}){const cut=ticket.corte;return <section className="mt-6 max-w-lg rounded bg-white p-5 text-slate-900"><h2 className="text-xl font-bold">{cut?'REPORTE Z':'AQUARIUM · TICKET'}</h2>{cut?<><p>Folio de corte #{cut.folio} · Ventas {cut.ventas}</p><p>Efectivo ${Number(cut.efectivo).toFixed(2)} · Tarjeta ${Number(cut.tarjeta).toFixed(2)}</p><p>IVA ${Number(cut.iva).toFixed(2)}</p><p className="text-xl font-bold">Total ${Number(cut.total).toFixed(2)}</p></>:<><p>Folio #{ticket.id}{ticket.pedido?` · Pedido #${ticket.pedido}`:''}</p><ul className="my-3 border-y py-2">{ticket.detalle?.map((line,i)=><li key={i} className="flex justify-between"><span>{line.nombre||line.concepto} × {line.cantidad}</span><span>${Number(line.subtotal).toFixed(2)}</span></li>)}</ul><p>Subtotal ${Number(ticket.subtotal).toFixed(2)}</p><p>IVA 16% ${Number(ticket.iva).toFixed(2)}</p><p className="text-xl font-bold">Total ${Number(ticket.total).toFixed(2)}</p><p>Pago: {ticket.metodo} · Recibido ${Number(ticket.recibido).toFixed(2)} · Cambio ${Number(ticket.cambio).toFixed(2)}</p><p className="text-xs">{ticket.fecha}</p></>}<button onClick={()=>window.print()} className="mt-3 rounded bg-slate-200 px-4 py-2 print:hidden">Imprimir</button></section>}

export default function POS(){
 const[code,setCode]=useState(''),[qr,setQr]=useState(''),[cart,setCart]=useState([]),[method,setMethod]=useState('efectivo'),[received,setReceived]=useState(''),[notice,setNotice]=useState(''),[ticket,setTicket]=useState(null),[orderId,setOrderId]=useState('');const input=useRef();
 const sub=cart.reduce((sum,p)=>sum+p.precio*p.cantidad,0),total=Math.round(sub*116)/100;
 async function scan(e){e.preventDefault();try{const p=await request('/pos/producto-codigo',{codigo:code});setCart(old=>{const next=[...old],row=next.find(x=>x.producto_id===p.id);if(row)row.cantidad++;else next.push({producto_id:p.id,nombre:p.nombre,precio:Number(p.precio),cantidad:1});return next});setCode('');input.current?.focus();setNotice('')}catch(error){setNotice(error.message)}}
 async function deliver(e){e.preventDefault();try{const data=await request('/pos/entregar',{codigo_qr:qr});setNotice(`Pedido #${data.pedido} entregado.`);setQr('')}catch(error){setNotice(error.message)}}
 async function charge(){try{const data=await request('/pos/cobrar',{items:cart,metodo:method,recibido:method==='efectivo'?Number(received):null});setTicket(data);setCart([]);setReceived('');setNotice('')}catch(error){setNotice(error.message)}}
 async function confirmOrder(e){e.preventDefault();try{const data=await request(`/pos/pedidos/${orderId}/confirmar`,{metodo:method,recibido:method==='efectivo'?Number(received):null});setTicket(data);setOrderId('');setReceived('');setNotice(`Pedido #${data.pedido} cobrado.`)}catch(error){setNotice(error.message)}}
 async function z(){try{const data=await request('/pos/corte-z',{});setTicket({corte:data})}catch(error){setNotice(error.message)}}
 return <><Head title="POS | AQUARIUM"/><main className="min-h-screen bg-[#0F172A] p-6 text-white"><header className="mb-6 flex flex-wrap items-center justify-between gap-3"><h1 className="text-3xl font-bold">AQUARIUM · Caja</h1><nav className="flex gap-4"><Link href="/pos/citas" className="text-cyan-300">Pagos veterinarios</Link><button onClick={z} className="rounded border border-cyan-400 px-3">Corte Z</button></nav></header><div className="grid gap-6 lg:grid-cols-3"><section className="lg:col-span-2"><form onSubmit={scan} className="flex gap-2"><input ref={input} autoFocus value={code} onChange={e=>setCode(e.target.value)} placeholder="Escanea código de barras" className="field"/><button className="rounded bg-[#00E5FF] px-5 font-bold text-slate-950">Buscar</button></form>{notice&&<p role="alert" className="mt-3 text-rose-300">{notice}</p>}<ul className="mt-4 space-y-2">{cart.map(p=><li key={p.producto_id} className="flex justify-between rounded bg-slate-800 p-4">{p.nombre} × {p.cantidad}<b>${(p.precio*p.cantidad).toFixed(2)}</b></li>)}</ul><form onSubmit={confirmOrder} className="mt-8 flex gap-2 rounded bg-slate-800 p-4"><input className="field" type="number" min="1" placeholder="Folio pedido web" value={orderId} onChange={e=>setOrderId(e.target.value)}/><button className="rounded bg-cyan-400 px-4 font-bold text-slate-950">Cobrar pedido reservado</button></form><form onSubmit={deliver} className="mt-4 flex gap-2 rounded bg-slate-800 p-4"><input className="field" placeholder="Token QR para entrega" value={qr} onChange={e=>setQr(e.target.value)}/><button className="rounded bg-cyan-400 px-4 font-bold text-slate-950">Entregar</button></form><p className="mt-2 text-xs text-slate-400">Confirma el pago con tarjeta en la terminal externa antes de registrarlo.</p></section><aside className="rounded-xl bg-slate-800 p-5"><h2 className="text-xl font-bold">Venta de mostrador</h2><p className="mt-4">Subtotal ${sub.toFixed(2)}</p><p>IVA 16% ${(total-sub).toFixed(2)}</p><p className="my-3 text-2xl font-bold">Total ${total.toFixed(2)}</p><select className="field" value={method} onChange={e=>setMethod(e.target.value)}><option value="efectivo">Efectivo</option><option value="tarjeta">Tarjeta (terminal externa)</option></select>{method==='efectivo'&&<label className="mt-3 block">Recibido<input className="field" type="number" min={total} step=".01" value={received} onChange={e=>setReceived(e.target.value)}/><small>Cambio ${Math.max(0,Number(received)-total).toFixed(2)}</small></label>}<button disabled={!cart.length} onClick={charge} className="mt-4 w-full rounded bg-[#00E5FF] p-3 font-bold text-slate-950">Cobrar venta</button></aside></div>{ticket&&<Ticket ticket={ticket}/>}</main></>;
}
