<?php
namespace App\Http\Controllers;

use App\Models\{CorteZ,Pedido,Producto,VentaPos}; use App\Services\AuditoriaService; use Illuminate\Http\Request; use Illuminate\Support\Facades\DB; use Illuminate\Validation\Rule; use Illuminate\Validation\ValidationException; use Inertia\Inertia;

class OperacionController extends Controller
{
    public function picking(){$orders=Pedido::with('items.producto','user')->whereIn('estatus',['Pendiente','Empacado','Listo en Mostrador'])->whereNotNull('metodo_pago')->orderByRaw("CASE WHEN tipo_entrega='click_collect' THEN 0 ELSE 1 END")->orderBy('fecha_recoleccion')->orderBy('hora_recoleccion')->get();$orders->each(fn($order)=>$order->setRelation('items',$order->items->sortBy(fn($item)=>$item->producto->pasillo??'ZZZ')->values()));return Inertia::render('Almacen/Picking',['pedidos'=>$orders]);}
    public function pos(){return Inertia::render('POS/Index');}
    public function clinicalPos(){return Inertia::render('POS/Clinicas');}
    public function estadoPedido(Request $request,Pedido $pedido,AuditoriaService $audit){$allowed=$pedido->tipo_entrega==='click_collect'?['Empacado','Listo en Mostrador']:['Empacado','Entregado'];$v=$request->validate(['estatus'=>['required',Rule::in($allowed)]]);$next=$pedido->estatus==='Pendiente'?'Empacado':($pedido->tipo_entrega==='click_collect'?'Listo en Mostrador':'Entregado');if($pedido->estatus==='Expirado'||$pedido->estatus==='Entregado'||$v['estatus']!==$next||!$pedido->metodo_pago)throw ValidationException::withMessages(['estatus'=>'El cambio de estado no es válido.']);$pedido->update(['estatus'=>$v['estatus'],'reservado_hasta'=>null,'expirado_at'=>$pedido->tipo_entrega==='click_collect'?now()->addHours(48):null]);$audit->registrar($request,'pedido.estatus:'.$pedido->id.':'.$v['estatus']);return back()->with('success','Estado de pedido actualizado.');}
    public function entregar(Request $request,AuditoriaService $audit){$v=$request->validate(['codigo_qr'=>'required|string']);$order=DB::transaction(function()use($v){$p=Pedido::where('codigo_qr',$v['codigo_qr'])->lockForUpdate()->firstOrFail();if($p->estatus!=='Listo en Mostrador'||($p->expirado_at&&$p->expirado_at->isPast()))throw ValidationException::withMessages(['codigo_qr'=>'Pase inválido, vencido o pedido aún no listo.']);$p->update(['estatus'=>'Entregado','expirado_at'=>null]);return $p;});$audit->registrar($request,'pedido.entregado:'.$order->id);return response()->json(['ok'=>true,'pedido'=>$order->id]);}
    public function productoPorCodigo(Request $request){$v=$request->validate(['codigo'=>'required|string|max:120']);$product=Producto::where('codigo_barras',$v['codigo'])->firstOrFail();return response()->json($product);}
    public function confirmarPedido(Request $request,Pedido $pedido,AuditoriaService $audit){$v=$request->validate(['metodo'=>'required|in:efectivo,tarjeta','recibido'=>'required_if:metodo,efectivo|nullable|numeric|min:0']);$result=DB::transaction(function()use($pedido,$v,$request){$this->lockCashier($request->user()->id);$order=Pedido::with('items.producto')->lockForUpdate()->findOrFail($pedido->id);if($order->estatus!=='Pendiente'||!$order->reservado_hasta||$order->reservado_hasta->isPast())throw ValidationException::withMessages(['pedido'=>'La reserva del pedido venció o ya fue confirmada.']);$received=$v['metodo']==='efectivo'?(float)$v['recibido']:(float)$order->total;if($received<(float)$order->total)throw ValidationException::withMessages(['recibido'=>'El efectivo recibido no cubre el total.']);$sale=VentaPos::create(['user_id'=>$request->user()->id,'detalle'=>$order->items->map(fn($i)=>['pedido_id'=>$order->id,'producto_id'=>$i->producto_id,'nombre'=>$i->producto->nombre,'cantidad'=>$i->cantidad,'precio_unitario'=>(float)$i->precio_unitario,'subtotal'=>(float)$i->subtotal])->all(),'metodo'=>$v['metodo'],'subtotal'=>$order->subtotal,'iva'=>$order->iva,'total'=>$order->total,'recibido'=>$received,'cambio'=>round($received-(float)$order->total,2),'created_at'=>now()]);$order->update(['reservado_hasta'=>null,'expirado_at'=>now()->addHours(48),'metodo_pago'=>$v['metodo']]);return ['id'=>$sale->id,'pedido'=>$order->id,'detalle'=>$sale->detalle,'subtotal'=>$sale->subtotal,'iva'=>$sale->iva,'total'=>$sale->total,'recibido'=>$sale->recibido,'cambio'=>$sale->cambio,'metodo'=>$sale->metodo,'fecha'=>$sale->created_at->toISOString()];});$audit->registrar($request,'pedido.cobrado:'.$pedido->id);return response()->json($result);}
    public function cobrarCita(Request $request,\App\Models\CitaVeterinaria $cita,AuditoriaService $audit){$v=$request->validate(['metodo'=>'required|in:efectivo,tarjeta','recibido'=>'required_if:metodo,efectivo|nullable|numeric|min:0']);$result=DB::transaction(function()use($request,$cita,$v){$this->lockCashier($request->user()->id);$appointment=\App\Models\CitaVeterinaria::lockForUpdate()->findOrFail($cita->id);if($appointment->estatus!=='Pendiente'||$appointment->pago_confirmado||!$appointment->reservado_hasta||$appointment->reservado_hasta->isPast())throw ValidationException::withMessages(['cita'=>'La cita/reserva ya venció o no está pendiente de cobro.']);$amount=(float)$appointment->costo;$received=$v['metodo']==='efectivo'?(float)$v['recibido']:$amount;if($received<$amount)throw ValidationException::withMessages(['recibido'=>'El efectivo recibido no cubre la consulta.']);$sale=VentaPos::create(['user_id'=>$request->user()->id,'detalle'=>[['cita_id'=>$appointment->id,'concepto'=>'Consulta veterinaria: '.$appointment->nombre_asistente,'cantidad'=>1,'subtotal'=>$amount]],'metodo'=>$v['metodo'],'subtotal'=>round($amount/1.16,2),'iva'=>round($amount-round($amount/1.16,2),2),'total'=>$amount,'recibido'=>$received,'cambio'=>round($received-$amount,2),'created_at'=>now()]);$appointment->update(['pago_confirmado'=>true,'metodo_pago'=>$v['metodo'],'reservado_hasta'=>null]);return ['venta'=>$sale->id,'cita'=>$appointment->id,'total'=>$amount,'cambio'=>$sale->cambio];});$audit->registrar($request,'cita.cobrada:'.$cita->id);return response()->json($result);}
    public function reembolsarCita(Request $request,\App\Models\CitaVeterinaria $cita,AuditoriaService $audit){$result=DB::transaction(function()use($request,$cita){$this->lockCashier($request->user()->id);$appointment=\App\Models\CitaVeterinaria::lockForUpdate()->findOrFail($cita->id);if($appointment->estatus!=='Cancelada'||!$appointment->pago_confirmado||!$appointment->reembolso_autorizado||$appointment->reembolso_pagado)throw ValidationException::withMessages(['cita'=>'No existe un reembolso autorizado pendiente.']);$amount=(float)$appointment->costo;$subtotal=round($amount/1.16,2);$tax=round($amount-$subtotal,2);$sale=VentaPos::create(['user_id'=>$request->user()->id,'detalle'=>[['cita_id'=>$appointment->id,'concepto'=>'Reembolso total consulta veterinaria','cantidad'=>-1,'subtotal'=>-$amount]],'metodo'=>$appointment->metodo_pago??'efectivo','subtotal'=>-$subtotal,'iva'=>-$tax,'total'=>-$amount,'recibido'=>0,'cambio'=>0,'created_at'=>now()]);$appointment->update(['reembolso_pagado'=>true]);return ['venta'=>$sale->id,'cita'=>$appointment->id,'reembolso'=>$amount,'metodo'=>$appointment->metodo_pago];});$audit->registrar($request,'cita.reembolsada:'.$cita->id);return response()->json($result);}
    public function cobrar(Request $request,AuditoriaService $audit){$v=$request->validate(['items'=>'required|array|min:1','items.*.producto_id'=>'required|exists:productos,id','items.*.cantidad'=>'required|integer|min:1','metodo'=>'required|in:efectivo,tarjeta','recibido'=>'required_if:metodo,efectivo|nullable|numeric|min:0']);$result=DB::transaction(function()use($v,$request){$this->lockCashier($request->user()->id);$sub=0;$details=[];foreach($v['items'] as $row){$p=Producto::whereKey($row['producto_id'])->lockForUpdate()->firstOrFail();if($p->stock<$row['cantidad'])throw ValidationException::withMessages(['items'=>'Stock insuficiente: '.$p->nombre]);$p->decrement('stock',$row['cantidad']);$line=round((float)$p->precio*$row['cantidad'],2);$sub+=$line;$details[]=['producto_id'=>$p->id,'nombre'=>$p->nombre,'cantidad'=>$row['cantidad'],'precio_unitario'=>(float)$p->precio,'subtotal'=>$line];}$sub=round($sub,2);$tax=round($sub*.16,2);$total=$sub+$tax;$received=$v['metodo']==='efectivo'?(float)$v['recibido']:$total;if($received<$total)throw ValidationException::withMessages(['recibido'=>'El efectivo recibido no cubre el total.']);$sale=VentaPos::create(['user_id'=>$request->user()->id,'detalle'=>$details,'metodo'=>$v['metodo'],'subtotal'=>$sub,'iva'=>$tax,'total'=>$total,'recibido'=>$received,'cambio'=>round($received-$total,2),'created_at'=>now()]);return ['id'=>$sale->id,'detalle'=>$details,'subtotal'=>$sub,'iva'=>$tax,'total'=>$total,'recibido'=>$received,'cambio'=>$sale->cambio,'metodo'=>$v['metodo'],'fecha'=>$sale->created_at->toISOString()];});$audit->registrar($request,'pos.venta:'.$result['id']);return response()->json($result);}
    public function corte(Request $request,AuditoriaService $audit){$report=DB::transaction(function()use($request){DB::table('users')->where('id',$request->user()->id)->lockForUpdate()->first();$last=CorteZ::where('user_id',$request->user()->id)->latest('created_at')->value('created_at');$sales=VentaPos::where('user_id',$request->user()->id)->when($last,fn($q)=>$q->where('created_at','>',$last))->orderBy('created_at')->get();$data=['desde'=>$last?\Carbon\Carbon::parse($last)->toISOString():now()->startOfDay()->toISOString(),'hasta'=>now()->toISOString(),'ventas'=>$sales->count(),'efectivo'=>(float)$sales->where('metodo','efectivo')->sum('total'),'tarjeta'=>(float)$sales->where('metodo','tarjeta')->sum('total'),'iva'=>(float)$sales->sum('iva'),'total'=>(float)$sales->sum('total'),'detalle'=>$sales->toArray()];$cut=CorteZ::create(['user_id'=>$request->user()->id,'reporte'=>$data,'created_at'=>now()]);$data['folio']=$cut->id;return $data;});$audit->registrar($request,'pos.corte_z:'.$report['folio']);return response()->json($report);}
    private function lockCashier(int $userId):void{DB::table('users')->where('id',$userId)->lockForUpdate()->first();}
}
